name: Run e2e tests

on:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with: { path: "~/.m2", key: "${{ runner.os }}-m2" }

    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: 6.2

    - name: Setup certificate stores
      env:
        KEYSTORE_JKS_B64: ${{ secrets.KEYSTORE_JKS_B64 }}
        TRUSTSTORE_JKS_B64: ${{ secrets.TRUSTSTORE_JKS_B64 }}
      run: |
        echo "$KEYSTORE_JKS_B64" | base64 -d > keystore.jks
        echo "$TRUSTSTORE_JKS_B64" | base64 -d > truststore.jks

    - name: Run tests
      env:
        API_PORT: 8080
        CLIENTS_INFO_PATH: ${{ secrets.CLIENTS_INFO_PATH }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        GATEWAY_PASSWORD: ${{ secrets.GATEWAY_PASSWORD }}
        GATEWAY_ROOT_URL: ${{ secrets.GATEWAY_ROOT_URL }}
        GATEWAY_USER: ${{ secrets.GATEWAY_USER }}
        KEYSTORE: keystore.jks
        KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
        OS_CONTAINER_NAME: ${{ secrets.OS_CONTAINER_NAME }}
        OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
        OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
        OS_USERNAME: ${{ secrets.OS_USERNAME }}
        RIO_READ_URL: ${{ secrets.RIO_READ_URL }}
        RIO_RECIPIENT_OIN: ${{ secrets.RIO_RECIPIENT_OIN }}
        RIO_SENDER_OIN: ${{ secrets.RIO_SENDER_OIN }}
        RIO_UPDATE_URL: ${{ secrets.RIO_UPDATE_URL }}
        STORE_HTTP_REQUESTS: true
        SURF_CONEXT_CLIENT_ID: ${{ secrets.SURF_CONEXT_CLIENT_ID }}
        SURF_CONEXT_CLIENT_SECRET: ${{ secrets.SURF_CONEXT_CLIENT_SECRET }}
        SURF_CONEXT_INTROSPECTION_ENDPOINT: ${{ secrets.SURF_CONEXT_INTROSPECTION_ENDPOINT }}
        TOKEN_ENDPOINT: ${{ secrets.TOKEN_ENDPOINT }}
        TRUSTSTORE: truststore.jks
        TRUSTSTORE_PASSWORD: ${{ secrets.TRUSTSTORE_PASSWORD }}
        WORKER_API_PORT: 8081

      run: lein test :e2e
